### ISSUE TITLE
Analyse flash usage and asuggest to uninstall flash if it is rarely used

### ISSUE THREAD

**Issue by rugk** [cpeterso/clear-flash-cookies#2]
Seriously, you should consider adding a suggestion to just uninstall flash? (long-term solution :D ) I'd say many users likely don't even know they do not need flash anymore. Maybe analyze the usage and display suggestion?

(requested in https://twitter.com/rugkme/status/932675303016730624)

**Comment by cpeterso** [comment]
Thanks for the suggestion. Flash is click-to-activate by default in Firefox 55+ so users are not running Flash unless they go out of their way to click and activate it. I'll update the add-on description (shown in on addons.mozilla.org and in Firefox's Adds-on Manager) to suggest uninstalling Flash with a link to [Mozilla's instructions for disabling or removing Flash](https://support.mozilla.org/en-US/kb/disable-or-remove-add-ons#w_how-to-disable-plugins).

The number of Firefox users who even have Flash installed is steadily shrinking. Mozilla tracks this information on the Firefox Hardware Report website:

https://hardware.metrics.mozilla.com/#goto-plugins

**Comment by rugk** [comment]
I'll think more than 50% is quite much already, but yeah… it's a thing.

**Comment by cpeterso** [comment]
I just updated the extension description on addons.mozilla.org to suggest disabling or removing Flash, including a link to SUMO instructions. (Unfortunately, the link is below the fold in the "Read more" section. The extension description in the Add-ons Manager will be updated automatically, but I don't know how soon.

https://addons.mozilla.org/firefox/addon/clear-flash-cookies/

Thanks again for the suggestion!
