### ISSUE TITLE
Firefox for Android 57

### ISSUE THREAD

**Issue by davidhedlund** [cpeterso/clear-flash-cookies#3]
https://addons.mozilla.org/en-US/firefox/addon/clear-flash-cookies/versions/ says
>Version 1.0.1 Released Nov. 20, 2017 129.2 KiB Works with Firefox for Android 48.0 and later, Firefox 42.0 and later

But I cannot install it on Firefox for Android 57.0.4.

Can you please update the maxversion for Firefox for Android in install.rdf?

**Comment by cpeterso** [comment]
Thanks for reporting this problem. Does Firefox for Android report that the maxversion is what is preventing installation? The extension's [manifest.json](https://github.com/cpeterso/clear-flash-cookies/blob/master/src/manifest.json) file does not specify a maxversion, so I assumed there would be no version limit. I don't have an Android device to test.

**Comment by davidhedlund** [comment]
> Does Firefox for Android report that the maxversion is what is preventing installation?

No, that was just an assumption.

**Comment by cpeterso** [comment]
I don't know if this is the problem you are hitting, but Firefox 56 for Android stopped support Flash on Android. In that case, there is no need to clear Flash cookies if there is no Flash Player to read them. :) I should probably update the extension's platform support so it no longer claims to support Android.

https://www.mozilla.org/en-US/firefox/android/56.0/releasenotes/

**Comment by davidhedlund** [comment]
It is still possible to install Flash on Android devices: https://adobe-flash-player.en.softonic.com/, https://en.softonic.com/articles/how-to-play-flash-on-android-devices

**Comment by cpeterso** [comment]
But does Firefox (56+) on Android still load Flash? I don't have an Android device I can test on.

**Comment by davidhedlund** [comment]
Can you please evaluate this later if you obtain an Android device?

**Comment by cpeterso** [comment]
Closing this issue because this extension is no longer relevant now that Adobe and Mozilla have EOL'd Flash.
